### ISSUE TITLE
Router pipeline only works with graphiql socket endpoint, not api socket

### ISSUE THREAD

**Issue by ssomnoremac** [absinthe-graphql/absinthe_plug#137]
* absinthe 1.4.1 (https://github.com/ssomnoremac/absinthe) (mix)
* absinthe_plug 1.4.1 (https://github.com/absinthe-graphql/absinthe_plug) (mix)
* absinthe_phoenix 1.4.0 (Hex package) (mix)
* absinthe_relay 1.4.2 (Hex package) (mix)
Elixir 1.5.2
Relay Modern

### Expected behavior
pipeline Context plug fires 

### Actual behavior
fires for `graphiql` but not from client client hitting `socket`

```
defmodule HyrWeb.Router do
  use Phoenix.Router
  import Plug.Conn
  import Phoenix.Controller
  
  pipeline :api do
    plug :accepts, ["json"]
    plug HyrWeb.Context
  end

  scope "/" do
    pipe_through :api

    forward "/socket", Absinthe.Plug,   # <- does NOT hit Context
      schema: HyrWeb.Schema,
      socket: HyrWeb.Channels.ShiftSocket

    forward "/graphiql", Absinthe.Plug.GraphiQL, # <- DOES hit Context
      schema: HyrWeb.Schema,
      interface: :simple,
      socket: HyrWeb.Channels.ShiftSocket

  end
end
```

the pipeline is just ignored for all my client calls. I don't see the `IO.inspect` that is shown below. I suspect it has something to do with `Absinthe.Plug` as that's the only thing that's different between the two endpoints. Don't know how it could be preventing `pipe_through`. Probably a socket issue but `graphiql` with sockets is getting the context pipe fine.

Here is my `Context.ex` but I am running the graphiql calls fine and can 100% confirm that `Context.ex` is doing what it is supposed to there.

```
defmodule HyrWeb.Context do
  @behaviour Plug
  import Plug.Conn

  def init(opts), do: opts
  def call(conn, _) do
    context = build_context(conn)
    IO.inspect [context: context]
    put_private(conn, :absinthe, %{context: context})
  end

  defp build_context(conn) do

    with %{} = user <- Hyr.Repo.get_by(Hyr.Accounts.User, phone: "+1-212-555-5555") do
      %{current_user: user} 
    else
      _ -> %{}
    end
  end

end
```

**Comment by ssomnoremac** [comment]
can confirm this only happens with websockets. Pipeline works from client over http

**Comment by benwilson512** [comment]
Hey @ssomnoremac.

All websocket connections are intercepted by Phoenix at the very top of your `endpoint.ex` module. They never go through the Router, any router pipelines, or your context plugs. This is just a general function of how websockets work, not anything absinthe specific.

If you want to set context on a websocket connection you need to do that over in the socket module you're using.

There seems to be a bit of confusion about the `socket` option. The `socket:` option is only valid for GraphiQL. All that it does is help GraphiQL figure out what URL to hit with websockets, because this is _different_ from the route that graphiql itself is on: It's whatever is in endpoint.ex. This option doesn't make any sense for the regular `Absinthe.Plug` because it's not trying to run any javascript that would be making connections.

**Comment by ssomnoremac** [comment]
Ahhhh, ok, thanks for the explanation. Explains why I wasn't getting any errors through the socket as well.

**Comment by JonRowe** [comment]
Apologies in advance for the noise maintainers!

If anyone else comes across this whilst trying to figure out how to use the Absinthe plug in a bare fashion as the readme describes, the trick is to use `Plug.Builder` rather than Router. e.g

```elixir
defmodule GraphQLPipeline do
  use Plug.Builder

  plug Absinthe.Plug.GraphQL, schema: Schema
end
```

(My use case is to wrap my GraphQL endpoint in Guardian auth seperate to my other routes :))
