### ISSUE TITLE
Accessing conn inside a resolver function

### ISSUE THREAD

**Issue by 1player** [absinthe-graphql/absinthe_plug#213]
How do I access the original conn (`%Plug.Conn{}`) inside a resolver function?

I need to generate a URL using the Phoenix router – i.e. `App.Router.Helpers.foo_path(conn, :index)` – and I can't find the original connection stored anywhere in the resolution context variable passed to my resolvers.

**Comment by 1player** [comment]
Found a workaround passing the endpoint to the router helpers: `App.Router.Helpers.foo_path(App.Endpoint, :index)`, but the original question still stands.

**Comment by benwilson512** [comment]
Hey @1player. The short version is that you don't because you don't want to. Absinthe and GraphQL are transport agnostic, and you're best off if you keep your resolver code that way too. Use plugs to set the absinthe context with any values you need from a conn inside your resolvers, and for phoenix helper functions you never need the actual conn, the `endpoint` will always suffice.
