### ISSUE TITLE
Supporting multipart request spec

### ISSUE THREAD

**Issue by ibash** [absinthe-graphql/absinthe_plug#215]
From what I can tell the file upload for absinthe came before this spec was written: https://github.com/jaydenseric/graphql-multipart-request-spec

The spec seems to be widely used now, is there interest in supporting it?

**Comment by benwilson512** [comment]
I believe the comment I made on it originally still applies: https://github.com/jaydenseric/graphql-multipart-request-spec/issues/4

In any case though, it should be entirely possible to build middleware that takes an HTTP request following this spec and transforms it into Absinthe.Plug standard.

**Comment by ibash** [comment]
Thanks for shedding light on this!

**Comment by matehat** [comment]
Hello! I just wanted to stop by and add some weight to the request to support the aforementioned spec. I'm writing an app in dart using the only GraphQL library available to it (https://pub.dev/packages/graphql_flutter) and they really only [support that spec](https://pub.dev/packages/graphql_flutter#graphql-upload) and not Absinthe's. 

I'm aware of the discussion and comments around nulls, but since the graphql community seems to settle around that, maybe that's the way forward?

**Comment by benwilson512** [comment]
The way forward is for someone to write a plug to support this. It will be very small, there's absolutely no need for this to be in Absinthe Plug core.

**Comment by 0x6a6f74726f** [comment]
Hi @benwilson512 if i would like to tackle this. My initial thought was to transform/align the `conn.body_params/params` so that `Absinthe.Plug.Request.parse/2` accepts the request.

My current observation is the following:

Expected "`conn`" before `Absinthe.Plug.Request.parse/2`

```
--- SNIP ---
body_params: %{
    "audio_file" => %Plug.Upload{
      content_type: "application/octet-stream",
      filename: "input.m4a",
      path: "/tmp/plug-1568/multipart-1568731479-371790761359256-3"
    },
    "query" => "mutation { --- SNIP --- }",
--- SNIP ---
 params: %{
    "audio_file" => %Plug.Upload{
      content_type: "application/octet-stream",
      filename: "input.m4a",
      path: "/tmp/plug-1568/multipart-1568731479-371790761359256-3"
    },
    "query" => "mutation { --- SNIP --- }",
},
```

Ouput of `conn` according to the "upload-spec"

```
--- SNIP ---
  body_params: %{
    "0" => %Plug.Upload{
      content_type: "audio/m4a",
      filename: "14.m4a",
      path: "/tmp/plug-1568/multipart-1568731773-18768148728598-3"
    },
    "map" => "{\"0\":[\"variables.audio\"]}",
    "operations" => "{\"operationName\":\"AddReview\",\"variables\":{\"audio\":null,\"publish\":true,\"spotId\":\"U3BvdDpmMGY3N2QyOC01ZjBkLTQ3MGEtODIxYS0wNjg1ZDk1OGI4ZTc=\"},\"query\":\"mutation AddReview($spotId: ID!, $audio: Upload!, $publish: Boolean){\\n  addReview(input: {is_published: true, spotId: $spotId, audio: $audio}){\\n    review {\\n      id\\n    }\\n  }\\n}\\n\"}"
--- SNIP ---
```

Is this a good approach? Could you, or someone else be so kind and point me in a direction?

**Comment by sescobb27** [comment]
for posterity, i adapted some solutions into this with some basic tests and a way to do an integration test [e2e_test.exs · GitHub](https://gist.github.com/sescobb27/8e42d39a78bddb0a728d260a0f2c29f6)
