### ISSUE TITLE
Dialyzer error using GraphiQL plug

### ISSUE THREAD

**Issue by woylie** [absinthe-graphql/absinthe_plug#233]
As soon as I configure a `default_url` for GraphiQL in my Phoenix router, I'm getting a dialyzer warning.

```elixir
forward "/graphiql", Absinthe.Plug.GraphiQL,
      default_url: {__MODULE__, :graphiql_default_url},
      schema: MyAppWeb.Schema

def graphiql_default_url, do: MyAppWeb.Endpoint.url() <> "/api"
```

or

```elixir
forward "/graphiql", Absinthe.Plug.GraphiQL,
      default_url: "/api",
      schema: MyAppWeb.Schema
```

Leads to:

```
lib/my_app_web/router.ex:1:no_return
Function __checks__/0 has no local return.
```

absinthe_plug 1.5.0
phoenix 1.5.4

**Comment by woylie** [comment]
This also happens when adding the `socket` or `socket_url` options. No change after upgrading to Phoenix 1.5.6.

**Comment by dfalling** [comment]
I get this as well if I just specify advanced:
```elixir
# works:
    forward("/graphiql", Absinthe.Plug.GraphiQL, schema: IdoWeb.Schema)
# fails:
    forward("/graphiql", Absinthe.Plug.GraphiQL, schema: IdoWeb.Schema, interface: :advanced)
```

**Comment by binaryseed** [comment]
Something similar appears to have been reported to phoenix itself:

https://github.com/phoenixframework/phoenix/issues/3393

I'm going to close this, since our direction forward involves removing GraphiQL from `absinthe_plug` itself. Please chime in if any of you know if there's an easy fix though...

I believe it can be worked around with the following annotation:

```elixir
@dialyzer {:no_return, {:__checks__, 0}}
```
