### ISSUE TITLE
Add support for transport batching

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe_plug#34]
Now that v1.2 has landed, it would be great to add transport batching support. It was initially contributed in v1.1 by @skosch in #23

**Comment by bruce** [comment]
As I mentioned in #23, it's going to require a pretty significant rewrite (which is good: our Blueprint tree gives us a much better footing). We can help direct efforts if someone wants to get started.

**Comment by skosch** [comment]
@bruce unless you were planning to tackle this yourself soon, I'm willing to take another shot at this, but I'd be grateful for some guidance – I haven't had a chance yet to scope out how your Blueprints are structured and/or how the plug has changed since 1.0. If one of you guys could point me to some of the key lines in the new codebase that would go a long way.

**Comment by bruce** [comment]
@skosch No problem -- and we have a lot of spinning plates right now, so help is certainly appreciated.

The biggest, pertinent changes moving things to Absinthe v1.2 was in this commit: https://github.com/absinthe-graphql/absinthe_plug/commit/e273507287c5681053a0c2b310c300d5c3d0abaa#diff-5794808f74bf04bf0f404486aa7e3a60

**Comment by karmajunkie** [comment]
anything new on transport-level batching recently?

**Comment by benwilson512** [comment]
Dunno if you saw but we did create https://github.com/absinthe-graphql/absinthe_plug/pull/43 which not only adds batching but executes the batch in such a way that things like the batching plugin can operate across the set of documents, leading to significantly less database access.

The reason that the PR isn't merged is that there will be a few changes that are waiting on https://github.com/absinthe-graphql/absinthe/pull/254 to go through.

**Comment by karmajunkie** [comment]
Missed that, thanks for the update!  Will check it out

**Comment by benwilson512** [comment]
Can someone comment on the current batching API expected by apollo / relay? Do they have commensurable expectations? Do they use the same endpoint for batching and non batching?

**Comment by skosch** [comment]
I believe Apollo and React-Relay-Network-Layer both use the basic format `[{query: ..., variables: ...}, ...]`. It seems that Apollo goes by the order of queries in that array, whereas RRNL adds an `id` field to identify them (but I guess you could just copy any extra fields over when present). Finally it appears that Apollo only lets you specify *one* endpoint, whereas RRNL allows you to set a different `batchUrl`. Ergo, for Apollo support, one plug would have to be handle both batch and non-batch formats.

(It's possible things have changed since I last experimented with this, so take the above with caution)

**Comment by tlvenn** [comment]
As far as Apollo is concerned, what @skosch holds true I believe
http://dev.apollodata.com/core/network.html#BatchingExplained

**Comment by tlvenn** [comment]
Same for Relay: https://github.com/nodkz/react-relay-network-layer#how-batching-works-internally

**Comment by benwilson512** [comment]
Supported in master / 1.3.0-rc.0
